name: Lib-ml Deployment

on: push
  # workflow_dispatch:
  #   inputs:
  #     tag_to_release:
  #       description: 'Optional: Specify the exact pre-release tag to promote (e.g., v1.2.3-pre.5). Leave blank to auto-detect latest.'
  #       required: false
  #       default: ''

jobs:
  delivery:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: bump_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: '.*'
          pre_release_branches: 'NONE'
          tag_prefix: v

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build wheel / sdist
        run: |
          python -m pip install --upgrade pip build  
          python -m build  
        
      - name: Get Artifact Filenames
        id: get_filenames
        run: |
          WHEEL_FILE=$(ls dist/*.whl | head -n 1)
          WHEEL_FILENAME=$(basename $WHEEL_FILE)
          echo "Found wheel file: $WHEEL_FILENAME"
          echo "wheel_filename=$WHEEL_FILENAME" >> $GITHUB_ENV

      - name: Create GitHub Release Page Entry
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump_version.new_version }}
          name: Release ${{ steps.bump_version.new_version}}
          body: |
            Release of version ${{ steps.bump_version.new_version }} for lib-ml.
    
             **Installation:**
            Download the `.whl` file from the assets below and install using pip:
            ```bash
            pip install https://github.com/${{ github.repository }}/releases/download/${{ steps.bump_version.new_version }}/${{ env.wheel_filename }}
            ```
            or add it to your requirements.txt
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}